#! /bin/bash

RPI_FILES=${HOME}/dhcp-setup/rpi
BACK=$HOME/back/edited
UDCONF=/etc/udhcpd.conf
UDHCPD=/etc/default/udhcpd 
INTERFACES=/etc/network/interfaces
HOSTAPD=/etc/default/hostapd
SYSCTLCONF=/etc/sysctl.conf
IP_FORWARD=/proc/sys/net/ipv4/ip_forward

# Created the next file. It did not exist
HOSTCONF=etc/hostapd/hostapd.conf 


function undo() {
	cp $RPI_FILES/udhcpd.conf /etc/.

}

function saveExisting {
	cp $UDCONF $BACK/.
}

saveExisting



