#! /bin/bash

cordova build android
# adb uninstall io.cordova.hellocordova
adb uninstall com.elvenware.resourceicons
# adb install platforms/android/build/outputs/apk/android-debug.apk
find . -iname app-debug.apk -exec adb install {} \;
