#! /bin/bash

function PartOne() {
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
	sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
	sudo apt-get update
	# apt-cache policy docker-ce
	sudo apt-get install -y docker-ce
#	sudo systemctl status docker
	sudo usermod -aG docker ${USER}
	su - ${USER}
	id -nG
	# echo "Now run Part Two"
}

PartOne
