#! /bin/bash

RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;36m'
NC='\033[0m' # No Color

# Updated December 2018, reviewed in April 2019
# See https://docs.docker.com/install/linux/docker-ce/ubuntu/
function PartOne() {
    sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo apt-key fingerprint 0EBFCD88
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) \
        stable"
    sudo apt-get update
    sudo apt-get install docker-ce docker-ce-cli containerd.io
    sudo groupadd docker
    sudo usermod -aG docker $USER    
    sudo systemctl enable docker
    echo "============================================="
    echo -e ${LIGHT_GREEN}"You should now log out and then log in again."${NC}
    echo "This should ensure that the docker group you"
    echo "joined is properly registered."
}

PartOne
