#! /bin/bash

function PartOne() {
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
	sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
	sudo apt-get update
	# apt-cache policy docker-ce
	sudo apt-get install -y docker-ce
#	sudo systemctl status docker
	sudo usermod -aG docker ${USER}
#	su - ${USER}
#	id -nG
	echo "You should now log out and then log in again."
	echo "This will ensure that the docker group you"
	echo "joined is properly registered."
}

PartOne
