#! /bin/bash

TEMP=$HOME/temp
WORDPRESS_DIR=wordpress

# Set $SCRIPT_DIR. Call before you navigate (CD) to another directory
function getScriptDirectory() {
	SOURCE="${BASH_SOURCE[0]}"
	while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
		SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
		SOURCE="$(readlink "$SOURCE")"
		# if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
		[[ $SOURCE != /* ]] && SOURCE="$SCRIPT_DIR/$SOURCE" 
	done
	SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
}

function tempDir() {
	if [ -d $TEMP ]; then
	  cd $TEMP
	  pwd
	else
	  mkdir $TEMP
	  cd $TEMP
	  pwd
	fi
}

function download() {
	if [ ! -d $WORDPRESS_DIR ]; then
		# sudo apt-get install php-curl php-gd php-mbstring php-mcrypt php-xml php-xmlrpc
		wget https://wordpress.org/latest.tar.gz
		tar -xzvf latest.tar.gz
		cd $WORDPRESS_DIR
		cp wp-config-sample.php wp-config.php
		# sudo chown -R www-data:www-data wp-content/
	fi
}

function mysqlSetup-Old {
	mysql -u root -p -e 'create database wordpress;'
	mysql -u root -p -e 'GRANT ALL PRIVILEGES ON wordpress.* TO "root"@"localhost" IDENTIFIED BY "foobar";'
	mysql -u root -p -e 'FLUSH PRIVILEGES;'
	mysql -u root -p -e 'use wordpress; show grants for 'root'@'localhost';'
}

function mysqlSetup {
	mysql -u root -p -e 'source '$SCRIPT_DIR'/wordpress.sql;'
}


getScriptDirectory
tempDir
download
mysqlSetup
