#! /bin/bash

TEMP=$HOME/temp

function tempDir() {
	if [ -d $TEMP ]; then
	  cd $TEMP
	  pwd
	else
	  mkdir $TEMP
	  cd $TEMP
	  pwd
	fi
}

function download() { 
	wget https://wordpress.org/latest.tar.gz
	tar -xzvf latest.tar.gz
}

function mysqlSetup-Old {
	mysql -u root -p -e 'create database wordpress;'
	mysql -u root -p -e 'GRANT ALL PRIVILEGES ON wordpress.* TO "root"@"localhost" IDENTIFIED BY "foobar";'
	mysql -u root -p -e 'FLUSH PRIVILEGES;'
	mysql -u root -p -e 'use wordpress; show grants for 'root'@'localhost';'
}

function mysqlSetup {
	mysql -u root -p -e 'source wordpress.sql;'
}


tempDir
download
mysqlSetup
