#! /bin/bash

PLATFORMS=platforms
PLUGINS=plugins/com.teamnemitoff.phonedialer
BOWER=www/bower_components

if [ -d "$PLATFORMS" ] ; then
    rm -r $PLATFORMS
fi

if [ -d "$PLUGINS" ] ; then
    rm -r $PLUGINS
    rm -r plugins/android.json
fi

if [ -d "$BOWER" ] ; then
    rm -r $BOWER
fi


