npm install "karma-script-launcher" --save-dev
npm install "karma-firefox-launcher" --save-dev
npm install "karma-chrome-launcher" --save-dev
npm install "karma-html2js-preprocessor" --save-dev
npm install "karma-requirejs" --save-dev
npm install "karma-qunit" --save-dev
npm install "karma-coffee-preprocessor" --save-dev
npm install "karma-phantomjs-launcher" --save-dev
npm install "karma" --save-dev
npm install "karma-commonjs" --save-dev
npm install "karma-junit-reporter" --save-dev
npm install "grunt" --save-dev
npm install "grunt-contrib-jshint" --save-dev
npm install "grunt-contrib-clean" --save-dev
npm install "grunt-contrib-compress" --save-dev
npm install "grunt-contrib-copy" --save-dev