#! /bin/bash

git clone git@github.com:charliecalvert/CloudNotes.git
git clone git@github.com:charliecalvert/JsObjects.git
git clone git@github.com:PacktPublishing/Unity-2020-Virtual-Reality-Projects-3rd-Edition-.git
git clone git@github.com:charliecalvert/charliecalvert.github.io.git
git clone git@github.com:coderzendo/coderzendo.github.io.git
git clone git@github.com:hrvey/combine-prs-workflow.git
git clone git@github.com:charliecalvert/create-jekyl-post.git
git clone git@github.com:docker/getting-started.git
git clone git@github.com:charliecalvert/docker-jekyll.git
git clone git@github.com:hunyoboy/dockerized-jekyll-nginx.git
git clone git@github.com:charliecalvert/elf-default.git
git clone git@github.com:charliecalvert/elven-code.git
git clone git@github.com:charliecalvert/elven-docker-jekyll-nginx.git
git clone git@github.com:charliecalvert/elven-firebase.git
git clone git@github.com:charliecalvert/elven-firebase.git
git clone git@github.com:charliecalvert/elven-jekyll.git
git clone git@github.com:charliecalvert/elven-site.git
git clone git@github.com:charliecalvert/elven-site-tools.git
git clone git@github.com:charliecalvert/elven-tools.git
git clone git@github.com:charliecalvert/elven-web.git
git clone git@github.com/firebase/firebaseui-web
git clone git@github.com:charliecalvert/isit-code.git
git clone git@github.com:charliecalvert/isit320-calvert-2017.git
git clone git@github.com:charliecalvert/isit320-calvert-2018.git
git clone git@github.com:charliecalvert/isit320-calvert-2019.git
git clone git@github.com:charliecalvert/isit322-calvert-2017.git
git clone git@github.com:charliecalvert/isit322-calvert-2018.git
git clone git@github.com:charliecalvert/isit322-calvert-2019.git
git clone git@github.com:charliecalvert/isit322-calvert-2020.git
git clone git@github.com:charliecalvert/jekyll-private.git
git clone git@github.com:BretFisher/jekyll-serve.git
git clone git@github.com:charliecalvert/move-photos.git
git clone git@github.com:charliecalvert/nginx-jekyll-docker.git
git clone git@github.com:jprichardson/node-fs-extra.git
git clone git@github.com:charliecalvert/poa.git
git clone git@github.com:imartinez/privateGPT.git
git clone git@github.com:charliecalvert/prog272-calvert-2018.git
git clone git@github.com:firebase/quickstart-js.git
git clone git@github.com:charliecalvert/sessionstore.git
git clone git@github.com:TabbyML/tabby.git
git clone git@github.com:charliecalvert/ubuntu-jekyll.git
git clone git@github.com:charliecalvert/walk-directories.git
