#! /bin/bash

PLATFORMS=platforms
PLUGINS=plugins/org.apache.cordova.geolocation
BOWER=www/bower_components

if [ -d "$PLATFORMS" ] ; then
    rm -r $PLATFORMS
fi

if [ -d "$PLUGINS" ] ; then
    rm -r $PLUGINS
fi

if [ -d "$BOWER" ] ; then
    rm -r $BOWER
fi


