#! /usr/bin/python3

# author: Charlie Calvert

import re

hand = open('config.xml')
for line in hand:
    line = line.rstrip()
    x = re.findall('<widget id="([^"]*)', line)
    if len(x) > 0:
        print('#! /bin/bash\n')        
        print('cordova build android')
        print('adb uninstall ' + x[0])
        print('adb install platforms/android/ant-build/CordovaApp-debug.apk\n')
        
