#! /bin/bash

echo "===================================================="
echo "This code loads only files with .spec in their name." 
echo "That is, it loads LoadTests.spec.js"
echo "That file loads our actual tests"
echo "===================================================="
 
jasmine-node --captureExceptions --verbose --runWithRequireJs --requireJsSetup ./Spec/requirejs-setup.js ./Spec/

# This would also work, but the above seems simpler:

# node node_modules/jasmine-node/lib/jasmine-node/cli.js --runWithRequireJs --requireJsSetup ./Spec/requirejs-setup.js ./Spec/
