#!/bin/bash

RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;36m'
NC='\033[0m' # No Color

function start() {
    sudo systemctl enable apache2
    sudo service apache2 start
}

function stop() {
    sudo service apache2 stop
    sudo systemctl disable apache2
}

function status() {
    sudo service apache2 status
}

while true; do
    message "Menu"
    echo -e "$LIGHT_GREEN  a) Start and Enable Apache"
    echo -e "$LIGHT_GREEN  b) Stop and Disable Apache"
    echo -e "$LIGHT_GREEN  c) Apache Status"
    echo -e "$LIGHT_RED  x) Exit"
    echo -e "\n$NC"
    read -p "Please make a selection: " eotuyx
    case $eotuyx in
        [Aa]* ) start false; continue;;
        [Bb]* ) stop false; continue;;
        [Cc]* ) status true; continue;;
        [XxQq]* ) break;;
        * )  -e "\n$NC" + "Please answer with c, r or x.";;
    esac
done
