#!/bin/bash

function checkStatus {
	if [ -n "$(git status --porcelain)" ]; then
	  echo "there are changes";
	  exit;
	else
	  echo "no changes";
	fi
}

echo "================"
cd $GIT_HOME/JsObjects
pwd
checkStatus

echo "================"
cd $GIT_HOME/writings
pwd
checkStatus

echo "================"
cd $GIT_HOME/CloudNotes
pwd
checkStatus

echo "================"
cd $GIT_HOME/prog272-calvert-2018
pwd
checkStatus

echo "================"
cd $GIT_HOME/isit322-calvert-2018
pwd
checkStatus
