#!/bin/bash

RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;36m'
NC='\033[0m' # No Color


function checkStatus {
	pwd
	if [ -n "$(git status --porcelain)" ]; then
	  echo  -e "$RED there are changes";
	  exit;
	else
	  echo  -e "$LIGHT_GREEN no changes";
	  git pull
	fi
}

echo "================"
cd $GIT_HOME/JsObjects
checkStatus

echo "================"
cd $GIT_HOME/writings
checkStatus

echo "================"
cd $GIT_HOME/CloudNotes
checkStatus

echo "================"
cd $GIT_HOME/charliecalvert.github.io
checkStatus

echo "================"
cd $GIT_HOME/prog109-calvert-2018
checkStatus

echo "================"
cd $GIT_HOME/prog109-notes
checkStatus

echo "================"
cd $GIT_HOME/isit320-calvert-2018
checkStatus
