#! /bin/bash

BASH_ALIAS=$HOME/Git/JsObjects/Utilities/SetupLinuxBox/.bash_aliases
BASH_ALIAS_LINK=$HOME/.bash_aliases
GIT_HOME=$HOME/Git
JSOBJECTS=$GIT_HOME/JsObjects
BIN_DIR=$HOME/bin

function message {
    echo
    echo =======================
    echo $1
    echo =======================
    echo
}

function gitSetup() {
    if [ ! -d "$GIT_HOME" ]; then
        echo "=> Creating Git directory"
        mkdir ~/Git
    else
        echo "=> Git directory already exists"
    fi
    cd ~/Git
    if [ ! -d "$JSOBJECTS" ]; then
        echo "=> Cloning JsObjects"
        git clone https://github.com/charliecalvert/JsObjects.git
    else
        echo "=> JsObjects already exists"
    fi
}

function setBashAliasAndSymbolicLinks() {
    if [ ! -L $BASH_ALIAS_LINK ]; then
        echo "=> Creating ~/.bash_aliases symbolic link"
        ln -s $BASH_ALIAS $BASH_ALIAS_LINK
        echo "=> Done"
    else
        echo "=> ~/.bash_aliases already exists"
    fi
    shopt -s expand_aliases
    source $BASH_ALIAS_LINK
    sh /home/ubuntu/Git/JsObjects/Utilities/SetupLinuxBox/CreateSymbolicLinks
}

function clean() {
    if [ -d "$GIT_HOME" ]; then
        echo "=> Deleting Git Directory and all contents"
        rm -rf $GIT_HOME
        echo "=> Done"
    else
        echo "=> Not deleting Git Directory because it does not exist"
    fi
    if [ -L "$BASH_ALIAS_LINK" ]; then
        echo "=> Deleting bash alias link"
        rm ~/.bash_aliases
        echo "=> Done"
    else
        echo "=> Not deleting bash alias link because it does not exist"
    fi
    
    if  [ -L "$BIN_DIR/CreateExpressProject" ]; then
        echo "=> Deleting symbolic links in bin directory"
        rm $BIN_DIR/CreateExpressProject
        rm $BIN_DIR/CreateAllExpress
        rm $BIN_DIR/check-karma-grunt-config
        rm $BIN_DIR/strip-triple-spaces
        rm $BIN_DIR/StartPythonWebServer
        rm $BIN_DIR/TestReady
        rm $BIN_DIR/TestCheck
        rm $BIN_DIR/elfgrepcomps
        rm $BIN_DIR/FixtureReady
        rm $BIN_DIR/InsertJadeExecGrunt.py
        echo "=> Done"
    else
        echo "=> -----------"
        echo "=> Not deleting symbolic links in bin directory "
        echo "=> because we think they don't exist "
        echo "=> -----------"
    fi
}

function run() {
    gitSetup
    setBashAliasAndSymbolicLinks
    
}


while true; do
    message "Menu"
    echo "r) Run Setup"
    echo "c) Delete files created by setup"
    echo "x) Exit"
    echo
    read -p "Please make a selection: " eotuyx
    case $eotuyx in
        [Cc]* ) clean; continue;;
        [Rr]* ) run; continue;;
        [Xx]* ) break;;
        * ) echo "Please answer with c, r or x.";;
    esac
done
