#! /usr/bin/env bash

#RED='\033[0;31m'
#LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
#BLUE='\033[1;36m'
NC='\033[0m' # No Color

BIN_DIR="$HOME"/bin

function createLink {
	if [ ! -L ~/bin/"$2" ]; then
		echo -e "$LIGHT_GREEN => Creating $1$2 $NC"
		ln -s "$1$2" ~/bin/.
	else
		echo -e "$YELLOW => ~/bin/$2 already exists $NC"
	fi
}

if [ ! -d "$BIN_DIR" ]; then
    echo "Creatings $BIN_DIR"
    mkdir "$BIN_DIR"
else
    echo "$BIN_DIR"' exists.'
fi

if [ ! -n "$JSOBJECTS" ]; then
    echo "=> Creating JSOBJECTS variable"
    JSOBJECTS=$HOME/Git/JsObjects
else
    echo "=> "JSOBJECTS environment variable already exists
fi

if [ ! -n "$ELF_UTILS" ]; then
    echo "=> Creating ELF_UTILS variable"
    ELF_UTILS=$JSOBJECTS/Utilities
else
    echo "=> "ELF_UTILS environment variable already exists
fi

if [ ! -n "$ELF_TEMPLATES" ]; then
    echo "=> Creating ELF_TEMPLATES variable"
    ELF_TEMPLATES=$ELF_UTILS/Templates
else
    echo "=> "ELF_TEMPLATES environment variable already exists
fi

if [ ! -n "$ELF_SCRIPTS" ]; then
    echo "=> Creating ELF_SCRIPTS variable"
    ELF_SCRIPTS="$ELF_TEMPLATES"/Scripts
else
    echo "=> "ELF_SCRIPTS environment variable already exists
fi

createLink "$ELF_UTILS"/NodeInstall/ CreateExpressProject
createLink "$ELF_UTILS"/NodeInstall/ CreateAllExpress
createLink "$ELF_UTILS"/NodeInstall/ check-karma-grunt-config
createLink "$ELF_UTILS"/SetupLinuxBox/ strip-triple-spaces
createLink "$ELF_UTILS"/SetupLinuxBox/ StartPythonWebServer
createLink "$ELF_UTILS"/NodeInstall/ TestReady
createLink "$ELF_UTILS"/NodeInstall/ TestCheck
createLink "$ELF_UTILS"/GrepScripts/ elfgrepcomps
createLink "$ELF_UTILS"/GrepScripts/ elfgrephtml
createLink "$ELF_UTILS"/GrepScripts/ elfgrepmd
createLink "$ELF_UTILS"/GrepScripts/ CheckBower
createLink "$ELF_TEMPLATES"/UnitTest/ FixtureReady
createLink "$ELF_TEMPLATES"/React/ ReactNpm
createLink "$ELF_TEMPLATES"/FindScripts/ FindNp
createLink "$ELF_TEMPLATES"/FindScripts/ FindNpDir
createLink "$ELF_TEMPLATES"/FindScripts/ FindNpPrettier
createLink "$ELF_TEMPLATES"/FindScripts/ package-json-test
createLink "$ELF_TEMPLATES"/React/ get-gist
createLink "$ELF_TEMPLATES/" get-template
createLink "$JSOBJECTS"/Python/Utils/ InsertJadeExecGrunt.py
createLink "$ELF_SCRIPTS"/ ShowPath
createLink "$ELF_SCRIPTS"/ GetFavicon
createLink "$ELF_SCRIPTS"/ GitIgnoreCheckForBad
createLink "$ELF_SCRIPTS"/ GitIgnoreTest
createLink "$ELF_SCRIPTS"/ GitIgnoreTester
createLink "$ELF_SCRIPTS"/ get-reveal
createLink "$ELF_SCRIPTS"/ pull-key-repos
createLink "$ELF_SCRIPTS"/ semver-inc
createLink "$ELF_SCRIPTS"/ update-all
createLink "$ELF_SCRIPTS"/ delete_node_modules
createLink "$ELF_SCRIPTS"/ get-tests
createLink "$ELF_SCRIPTS"/ bower-components
createLink "$ELF_UTILS"/SetupLinuxBox/ Provision
