#! /bin/bash


BIN_DIR="$HOME"/bin

if [ ! -d "$BIN_DIR" ]; then
    echo 'Creating '"$BIN_DIR"
    mkdir "$BIN_DIR"
else
    echo "$BIN_DIR"' exists.'
fi

if [ ! -n "$JSOBJECTS" ]; then
    echo "=> Creating JSOBJECTS variable"
    JSOBJECTS=$HOME/Git/JsObjects
else
    echo "=> "JSOBJECTS environment variable already exists
fi

if [ ! -n "$ELF_UTILS" ]; then
    echo "=> Creating ELF_UTILS variable"
    ELF_UTILS=$JSOBJECTS/Utilities
else
    echo "=> "ELF_UTILS environment variable already exists
fi

if [ ! -n "$ELF_TEMPLATES" ]; then
    echo "=> Creating ELF_TEMPLATES variable"
    ELF_TEMPLATES=$ELF_UTILS/Templates
else
    echo "=> "ELF_TEMPLATES environment variable already exists
fi

if [ ! -n "$ELF_SCRIPTS" ]; then
    echo "=> Creating ELF_SCRIPTS variable"
    ELF_SCRIPTS=$ELF_TEMPLATES/Scripts
else
    echo "=> "ELF_SCRIPTS environment variable already exists
fi

ln -s $ELF_UTILS/NodeInstall/CreateExpressProject ~/bin/.
ln -s $ELF_UTILS/NodeInstall/CreateAllExpress ~/bin/.
ln -s $ELF_UTILS/NodeInstall/check-karma-grunt-config ~/bin/.
ln -s $ELF_UTILS/SetupLinuxBox/strip-triple-spaces ~/bin/.
ln -s $ELF_UTILS/SetupLinuxBox/StartPythonWebServer ~/bin/.
ln -s $ELF_UTILS/NodeInstall/TestReady ~/bin/.
ln -s $ELF_UTILS/NodeInstall/TestCheck ~/bin/.
ln -s $ELF_UTILS/GrepScripts/elfgrepcomps ~/bin/.
ln -s $ELF_UTILS/GrepScripts/CheckBower ~/bin/.
ln -s $ELF_TEMPLATES/UnitTest/FixtureReady ~/bin/.
ln -s $JSOBJECTS/Python/Utils/InsertJadeExecGrunt.py ~/bin/.
ln -s $ELF_SCRIPTS/ShowPath ~/bin/.
ln -s $ELF_SCRIPTS/GitIgnoreTest ~/bin/.
