#!/bin/bash

RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;36m'
NC='\033[0m' # No Color

SLB=~/Git/JsObjects/Utilities/SetupLinuxBox

# Update
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y
sudo apt-get install build-essentials -y

# Git
mkdir ~/Git
cd ~/Git
git clone https://github.com/charliecalvert/JsObjects

# SSH
if [ -z "$SSH_AUTH_SOCK" ] ; then
    eval `ssh-agent`
fi
"$SLB/SetupSsh"
cd ~/.ssh
ssh-add id_rsa
# ssh-copy-id -i id_rsa bcuser@192.168.2.34

# Create Next Script to run after reboot
RUS=~/RunUbuntuSetup
echo -e '#!/bin/bash' > $RUS
echo -e '' >> $RUS
echo -e 'cd ~/Git/JsObjects/Utilities/SetupLinuxBox' >> $RUS
echo -e './UbuntuSetup' >> $RUS
chmod +x $RUS

echo -e "You should run ${LIGHT_GREEN}sudo reboot${NC} to re-start the system."
echo -e "Then execute ${LIGHT_GREEN}~/RunUbuntuSetup'${NC}"
