#!/bin/bash

SLB=~/Git/JsObjects/Utilities/SetupLinuxBox

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y
sudo apt-get install build-essentials -y

mkdir ~/Git
cd ~/Git
git clone https://github.com/charliecalvert/JsObjects

"$SLB/SetupSsh"
cd ~/.ssh
ssh-add id_rsa
// ssh-copy-id -i id_rsa bcuser@192.168.2.34

RUS=~/RunUbuntuSetup
echo -e '#!/bin/bash' > $RUS
echo -e '' >> $RUS
echo -e 'cd ~/Git/JsObjects/Utilities/SetupLinuxBox' >> $RUS
echo -e './UbuntuSetup' >> $RUS
chmod +x $RUS

echo -e 'You should reboot the system and then execute ~/RunUbuntuSetup'
