#! /bin/bash


shopt -s expand_aliases
source ~/.bash_aliases

alias

function title() {
	echo -e "\n==============="
	echo $1
	echo "==============="
}

function other() {
	title isit322-calvert-2016
	i3c && git pull

	title prog270-calvert-2016
	cd ~/Git/prog270-calvert-2016
	git pull
}

function spring() {
    title prog219-calvert-2016
    p9c && pwd && git pull

    title prog272-calvert-2016
    p2c && pwd && git pull
}

title gitio
gitio && pwd && git pull

title CloudNotes
cn && pwd && git pull

title JsObjects
jo && pwd && git pull

title Writing
wt && pwd && git pull

title ElfSite
elfsite && pwd && git pull

title elven-assignments
elfa && pwd && git pull

title elven-tools
elventools
pwd
git pull

spring
