#! /usr/bin/env bash

RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;36m'
NC='\033[0m' # No Color

NORMAL_PORT=true

if [[ -z $1  ]]; then
    echo "======================================================"
    echo -e $LIGHT_RED"Aborting. "$YELLOW"You must pass in the name of the project to create."$NC       
    echo "Example:"
    echo -e $LIGHT_GREEN"    CreateExpressProject MyProject"$NC
    echo "======================================================"
    exit
fi

function message {
    echo
    echo =======================
    echo "$1"
    echo =======================
    echo
}

while true; do
    message "Menu"
    echo -e "$LIGHT_GREEN  n) Create Normal Project on Port 30025"
    echo -e "$LIGHT_GREEN  s) Create Server Project on Port 30026 with SERVER_PORT"
#    echo -e "$LIGHT_RED    x) Exit"
#    echo -e "$LIGHT_RED    q) Exit"
    echo -e "\n$NC"
    read -p "Please make a selection: "  eotuyx
    case $eotuyx in
        [Nn]* ) NORMAL_PORT=true; break;;
        [Ss]* ) NORMAL_PORT=false; break;;        
#        [XxQq]* ) break;;
        * )  -e "\n$NC" + "Please answer with n or s.";;
    esac
done

function checkEnvironmentVariable {
    if [ -n "$2" ]
    then
        echo -e "\tOK: \$$1 = $2"
    else
        echo "======================================"
        echo -e " You are missing the \$$1" environment variable
        echo -e " Do you define it in $HOME/.bash_aliases?"
        echo -e " A sample .bash_aliases file is found in:"
        echo -e "\t$JSOBJECTS/Utilities/SetupLinuxBox"
        echo "======================================"
        exit
    fi
}

checkEnvironmentVariable ELF_TEMPLATES $ELF_TEMPLATES

# Create an express app and run npm install
express --view=pug $1
cd $1

npm install

# Setup bower and bootstrap
cp $ELF_TEMPLATES/bower.json .
cp $ELF_TEMPLATES/.bowerrc .
cp $ELF_TEMPLATES/nodemon.json .
bower install bootstrap --save
bower install jquery --save

function setPortToNormal() {
    # Set up port
    if [[ $NORMAL_PORT == true ]]; then
        sed -i -- 's/3000/30025/g' bin/www
    else    
        sed -i "s/process.env.PORT || '3000'/process.env.SERVER_PORT || '30026'/" bin/www
    fi

    sed -i "s/server.listen(port)/server.listen(port, () => { console.log('Listening on port', port); })/" bin/www
}

function createProject() {
    # Set nodemon and favicon
    sed -i -- 's/node\s/nodemon /g' package.json
    cp $ELF_TEMPLATES/Images/favicon.ico public/.

    # Set title, create README and control.js
    sed -i -- 's/Express/'$1'/g' routes/index.js
    echo -e "# $1\n\nby Charlie Calvert" >> README.md
    #echo -e "\$(document).ready(function() { 'use strict'; \n});" >> public/javascripts/control.js
    echo -e "window.onload = () => { };" >> public/javascripts/control.js

    # Add use strict
    sed -i "s/{$/{ 'use strict';/" routes/index.js
    sed -i "s/{$/{ 'use strict';/" routes/users.js
    sed -i "s/next) {/next) { 'use strict';/" app.js

    # Link in Bootstrap with layout.jade
    sed -i "/style.css')/r "$ELF_TEMPLATES"/BootstrapLayout.json" views/layout.pug
    sed -i "/style.css')/r "$ELF_TEMPLATES"/Favicon.json" views/layout.pug
    exit
}

setPortToNormal
createProject $1
