#! /usr/bin/env bash

npm i -g eslint eslint-plugin-flowtype eslint-plugin-import
npm i -g eslint-plugin-jsx-a11y eslint-plugin-react
npm i -g babel-eslint eslint-plugin-react-hooks
npm i -g eslint-config-react-app eslint-config-airbnb-base
npm i -g eslint-config-fortech-react eslint-plugin-react

# npm remove -g eslint eslint-config-react-app eslint-plugin-flowtype eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react babel-eslint eslint-plugin-react-hooks eslint-config-airbnb-base eslint-config-fortech-react

# npm install -g @typescript-eslint/eslint-plugin @typescript-eslint/parser
