#! /usr/bin/env bash

npm install -g eslint eslint-plugin-flowtype eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react babel-eslint eslint-plugin-react-hooks eslint-config-react-app eslint-config-airbnb-base eslint-config-fortech-react

# npm remove -g eslint eslint-config-react-app eslint-plugin-flowtype eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react babel-eslint eslint-plugin-react-hooks eslint-config-airbnb-base eslint-config-fortech-react

# npm install -g @typescript-eslint/eslint-plugin @typescript-eslint/parser
