#!/bin/bash

npm config set prefix ~/npm

function message {
    echo
    echo =======================
    echo $1
    echo =======================
    echo
}

function clean() {
    message "Clean"
}

function essentials() {
    message "Installing Essentials"
    npm install -g grunt-cli
    npm install -g express-generator
    npm install -g create-react-app
    npm install -g nodemon
    npm install -g bower
    npm install -g jade
    npm install -g pug-cli
    npm install -g js-beautify
    npm install -g html-beautify
}

function unitTests {
    message "Installing Unit Test related code"
    npm install -g mocha
    npm install -g karma-cli
    npm install -g phantomjs-prebuilt
}

echo "You start with $# positional parameters"

while [ "$1" != "" ]; do
    case $1 in
        [Cc]* ) clean; shift;;
        [Ee]* ) essentials; shift;;
        [Uu]* ) unitTests; shift;;
        [Xx]* ) break;;
    esac
done
