#! /usr/bin/env bash

npm config set prefix ~/npm

function message {
    echo
    echo =======================
    echo "$1"
    echo =======================
    echo
}

function clean() {
    message "Clean"
}

function essentials() {
    message "Installing Essentials"
    npm install -g npm@latest nodemon npm-check-updates
}

function essentials_old() {
    message "Installing Old Essentials"
    npm install -g eslint babel-eslint
    npm install -g eslint-plugin-react
    npm install -g create-react-app
    npm install -g grunt-cli bower
    npm install -g elf-express-generator express-generator    
    npm install -g pug-cli
    npm install -g prettier js-beautify html-beautify
    "${NODE_UTILS}"/EsLintInstall
}

function uninstall_essentials_old() {
    message "Installing Old Essentials"
    npm uninstall -g eslint babel-eslint
    npm uninstall -g eslint-plugin-react
    npm uninstall -g create-react-app
    npm uninstall -g grunt-cli bower
    npm uninstall -g elf-express-generator express-generator    
    npm uninstall -g pug-cli
    npm uninstall -g prettier js-beautify html-beautify
    "${NODE_UTILS}"/EsLintInstall
}

function unitTests {
    message "Installing Unit Test related code"
    # npm install -g mocha
    # npm install -g karma-cli
    # npm install -g phantomjs-prebuilt
}

echo "You start with $# positional parameters"

while [ "$1" != "" ]; do
    case $1 in
        [Cc]* ) clean; shift;;
        [Ee]* ) essentials; shift;;
        [Oo]* ) essentials_old; shift;;
        [Rr]* ) uninstall_essentials_old; shift;;
        [Uu]* ) unitTests; shift;;
        [Xx]* ) break;;
    esac
done
