#! /bin/bash

cp $ELF_UNIT_TEST/Gruntfile.js .
cp $ELF_UNIT_TEST/karma.conf.js .
cp $ELF_UNIT_TEST/.jscsrc .
sed -i '/\s\s}$/r '$ELF_UNIT_TEST'/DevDependencies.json' package.json
js-beautify -r package.json 
mkdir spec
cp $ELF_UNIT_TEST/test-basic.js spec/.
strip-triple-spaces app.js
# npm install
echo "============================================="
echo "Set up node_modules and public/components (npm, bower)."
echo "Run the following command to test your tests:"
echo -e "\ngrunt check"
echo -e "\ngrunt test"
echo "============================================="

