#!/bin/bash

RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;36m'
NC='\033[0m' # No Color

ESLINT_DIR=/tmp/eslint-dir
GIST_ELF_DEBUG_ENZYME=https://gist.github.com/51daef341699943b07c9570c3ad2cbab.git
GIST_ESLINTRC=https://gist.github.com/c5952541925c04479150bbd8c40feac6.git

function message {
    echo
    echo =======================
    echo "$1"
    echo =======================
    echo
}

function removeDir {		
	if [ -d $ESLINT_DIR ]; then		
		rm -rf $ESLINT_DIR
		echo "Deleted " $ESLINT_DIR
	fi
}

function getGist() {
	removeDir
	git clone $1 $ESLINT_DIR
	cp -v $ESLINT_DIR/$2 .
	removeDir
}

function runCommand() {
	case $1 in
		"elfdebug") getGist $GIST_ELF_DEBUG_ENZYME ElfDebugEnzyme.js ;;
		"eslintrc") getGist $GIST_ESLINTRC .eslintrc.json ;;
	esac
}

function runAll() {
	runCommand "elfdebug"
	runCommand "eslintrc"
}

while true; do
    message "Menu"
    echo -e "$LIGHT_GREEN Ubuntu"
    echo -e "$LIGHT_GREEN  a) Run All (ESLintRc and ElfDebugEnzyme)"
    echo -e "$LIGHT_GREEN  b) Get ElfDebugEnzyme"
    echo -e "$LIGHT_GREEN  c) Get .eslintrc"
    echo -e "$LIGHT_RED  x) Exit (You should source .bashrc when done)"
    echo -e "\n$NC"
    read -p "Please make a selection: " eotuyx
    case $eotuyx in
        [Aa]* ) runAll false; continue;;
        [Bb]* ) runCommand "elfdebug"; continue;;
        [Cc]* ) runCommand "eslintrc"; continue;;
        [XxQq]* ) break;;
        * )  -e "\n$NC" + "Please answer with a, b, c or x.";;
    esac
done

echo "All Done"
