#! /usr/bin/env bash

RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;36m'
NC='\033[0m' # No Color

START_DIR=$HOME'/Git/JsObjects/JavaScript/React/'

function check-return-value {
    retVal=$?
    if [ $retVal -ne 0 ]; then
        echo -e ${LIGHT_RED}"Error"${NC}
    else
        echo -e ${LIGHT_GREEN}"Ok"${NC}
    fi
}

function check-dir {
    cd $START_DIR
    cd $1
    pwd
    npm audit --json > elf-audit.json
    check-return-value
}

function get-directories-containing-package-json {
    FindNp package.json | xargs -I{} dirname {} | xargs printf "check-dir %s\n" | sort
}

#check-dir ./drawer-menu
#check-dir ./ElfExpressServer
#check-dir ./ElfExpressServer/client
#check-dir ./ElfExpressServer/server
#check-dir ./higher-order-component
#check-dir ./MaterialBrowserify
#check-dir ./ReactEs6/ReactBasics
#check-dir ./ReactEs6/ReactEs6Bower
#check-dir ./ReactEs6/ReactEs6Browserify
#check-dir ./ReactFetchTests
#check-dir ./react-native-test
#check-dir ./ReactNativeTesting/EnzymeBasics
#check-dir ./ReactNativeTesting/SnapShotBasics
#check-dir ./react-simple
#check-dir ./react-webpack-simple
#check-dir ./redux-simple
#check-dir ./RestBoiler
#check-dir ./RestExpress
#check-dir ./simple-components
check-dir ./simple-radio-buttons
#check-dir ./simple-state
#check-dir ./style-guide-examples
#check-dir ./todo-redux
#check-dir ./webpack-simple
#check-dir ./gatsby-site
