#! /usr/bin/env bash

RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;36m'
NC='\033[0m' # No Color

ESLINT_DIR=/tmp/eslint-dir
SANITY_APP_TEST=https://gist.github.com/charliecalvert/64d2a63ed40e116dd20f55e98116baa6
ELVEN_SANITY_TESTS=https://github.com/charliecalvert/elven-sanity.git

function message {
    echo
    echo =======================
    echo "$1"
    echo =======================
    echo
}

function removeDir {
    if [ -d $ESLINT_DIR ]; then
        rm -rf $ESLINT_DIR
        echo "Deleted " $ESLINT_DIR
    fi
}

function getGist() {
    removeDir
    git clone $1 $ESLINT_DIR
    echo -e "NUMBER 2 = $2"
    cp -v $ESLINT_DIR/$2 .
}

function runCommand() {
    case $1 in
        "restBasicsAppTest") getGist $ELVEN_SANITY_TESTS Sanity.App.test.js ;;
        "gitExplorerMicroStructureTest") getGist $ELVEN_SANITY_TESTS Sanity.MicroStructure.js ;;
        
    esac    
}

function runAll() {
    runCommand "restBasicsAppTest"
}


while true; do
    message "Menu"
    echo -e "$LIGHT_GREEN Gists"
    echo -e "$LIGHT_GREEN  a) Week03 Rest Basics App Test"
    echo -e "$LIGHT_GREEN  b) Git Explorer Micros Structure Tests"
    echo -e "$LIGHT_RED  x) Exit"
    echo -e "\n$NC"
    read -p "Please make a selection: " eotuyx
    case $eotuyx in
        [Aa]* ) runCommand "restBasicsAppTest"; continue;;
        [Bb]* ) runCommand "gitExplorerMicroStructureTest"; continue;;
        [XxQq]* ) break;;
        * )  -e "\n$NC" + "Please answer with a, b, c or x.";;
    esac
done

echo "All Done"
