#! /bin/bash

function message {
    echo
    echo =======================
    echo "$1"
    echo =======================
    echo
}

message "Pulling charliecalvert.github.io"
cd $HOME/Git/charliecalvert.github.io
pwd
git pull

message "Pulling CloudNotes"
cd $HOME/Git/CloudNotes
pwd
git pull

message "Pulling JsObjects"
cd $HOME/Git/JsObjects
pwd
git pull
