#! /bin/bash

function message {
    echo
    echo =======================
    echo "$1"
    echo =======================
    echo
}

message "Pulling charliecalvert.github.io on $HOSTNAME" 
cd $HOME/Git/charliecalvert.github.io
pwd
git pull

message "Pulling CloudNotes on $HOSTNAME"
cd $HOME/Git/CloudNotes
pwd
git pull

message "Pulling JsObjects on $HOSTNAME"
cd $HOME/Git/JsObjects
pwd
git pull
