#! /usr/bin/env bash

RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;36m'
NC='\033[0m' # No Color

sudo apt-get update && sudo apt upgrade -y && sudo apt dist-upgrade -y && sudo apt autoremove

function message {
    echo
    echo =======================
    echo -e "$1"
    echo =======================
    echo
}

if [ -f /var/run/reboot-required ]; then
  message "$LIGHT_RED Reboot required $NC"
else
  message "$LIGHT_GREEN All done $NC"
fi

