#! /bin/bash

# If we have renamed our project in config.xml, then this script
# makes sure the change is propogated throughout the project.

LINK_DIR=platforms/android

if [ -d "$LINK_DIR" ]; then 
  if [ -L "$LINK_DIR" ]; then
    # Symbolic link specific commands
    rm "$LINK_DIR"
  else
    # Directory commands    
    cordova platform remove android
  fi
fi

cordova platform add android
