#! /usr/bin/python3

# author: Charlie Calvert
# description: Create the text for a file to build, uninstall and install
#    a Cordova application. Pipe the text produced by this script
#    into a file called install. For instance:
#
#        ./GetCordovaUrl > install
#        chmod +x install
#        ./install

import re

hand = open('config.xml')
for line in hand:
    line = line.rstrip()
    x = re.findall('<widget id="([^"]*)', line)
    if len(x) > 0:
        print('#! /bin/bash\n')        
        print('cordova build android')
        print('adb uninstall ' + x[0])
        print('adb install platforms/android/ant-build/CordovaApp-debug.apk\n')
        
