#! /bin/bash

GREP='grep -r --include=*.js --exclude-dir=node_modules --exclude-dir=components --exclude-dir=.config --exclude-dir=.mozilla'
C=''
for i in "$@"; do 
    C="$C \"${i//\"/\\\"}\""
done
echo -e '\n'Running:'\n'${GREP} ${C}'\n\nResults:'
bash -c "${GREP} ${C}"

echo -e '\nExit Code:' $?
